import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Common/Header/Header";
import { Oswald } from 'next/font/google';
import Footer from "@/components/Common/Footer/Footer";

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], // Choose weights you need
  variable: '--font-oswald', // Optional: for CSS variable usage
  display: 'swap',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={oswald.className}
      >
        <Header/>
        <div className="min-h-screen">
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
